name: CI

# Events that trigger the workflow
on:
  # Runs on all pushes to branches
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
  # Runs on all PRs
  pull_request:
  # Manual Dispatch
  workflow_dispatch:

concurrency:
  # Behavior:
  # - Group all pull requests: latest push cancels previous ones
  # - Group all branches:
  #   - If main/version- branches: run serially
  #   - Else, latest push cancels previous ones
  group: >
    ${{
      (github.event_name == 'pull_request' && format('pr-{0}', github.event.pull_request.number)) ||
      (github.event_name == 'push' && format('branch-{0}', github.ref_name)) ||
      ''
    }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' || !(startsWith(github.ref_name, 'version-') || github.ref_name == 'main' || github.ref_name == 'dev') }}

jobs:
  precheck:
    runs-on: ubuntu-24.04
    name: Run the Reticle Stitcher
    steps:
      - uses: actions/checkout@v6
      - name: Setup Nix
        uses: ./.github/actions/setup_nix
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          nix_cache_domain: ${{ vars.NIX_CACHE }}
          nix_public_key: ${{ vars.NIX_PUBLIC_KEY }}
      - name: Build with Nix
        uses: ./.github/actions/build_nix
        with:
          nix_system: x86_64-linux
      - name: Check Nix
        run: |
          sudo du -hs /nix/store/* | sort -h | tail -n 10
          sudo tree /nix/store/*-librelane || true
      - name: Run the Reticle Stitcher
        run: |
          nix develop --command make stitch
          nix develop --command make stitch-obfuscate
          nix develop --command make stitch-empty
      - name: Upload Run
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: run
          path: runs/*
